-- Rivermind schema v1
-- Event-sourced temporal memory layer: observations (authoritative append-only log)
-- plus two projections (state, narratives) that are rebuildable from observations.
-- FTS5 indexes observation content for topic search without embeddings.
-- Entity ids are prefixed strings (e.g. "obs-<uuid>") generated by the adapter.

CREATE TABLE observations (
    id              TEXT    PRIMARY KEY NOT NULL,
    content         TEXT    NOT NULL,
    kind            TEXT    NOT NULL,
    subject         TEXT,
    attribute       TEXT,
    value           TEXT,
    observed_at     TEXT    NOT NULL,
    recorded_at     TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    source_model    TEXT,
    session_id      TEXT,
    superseded_by   TEXT    REFERENCES observations(id),

    CHECK (id LIKE 'obs-%'),
    CHECK (kind IN ('fact', 'event', 'reflection')),
    CHECK (kind != 'fact' OR (subject IS NOT NULL AND attribute IS NOT NULL)),
    CHECK (superseded_by IS NULL OR kind = 'fact'),
    CHECK (value IS NULL OR json_valid(value))
);

CREATE INDEX idx_observations_observed_at ON observations(observed_at);

CREATE TABLE state (
    subject             TEXT    NOT NULL,
    attribute           TEXT    NOT NULL,
    current_value       TEXT,
    current_since       TEXT    NOT NULL,
    source_observation  TEXT    NOT NULL REFERENCES observations(id),

    PRIMARY KEY (subject, attribute),
    CHECK (current_value IS NULL OR json_valid(current_value))
);

CREATE INDEX idx_state_subject ON state(subject);

CREATE TABLE narratives (
    id                  TEXT    PRIMARY KEY NOT NULL,
    content             TEXT    NOT NULL,
    topic               TEXT,
    period_start        TEXT    NOT NULL,
    period_end          TEXT    NOT NULL,
    source_observations TEXT    NOT NULL,
    generated_at        TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    superseded_by       TEXT    REFERENCES narratives(id),

    CHECK (id LIKE 'nar-%'),
    CHECK (json_valid(source_observations))
);

CREATE VIRTUAL TABLE observations_fts USING fts5(
    content,
    content=observations,
    content_rowid=rowid
);

CREATE TRIGGER observations_ai AFTER INSERT ON observations BEGIN
    INSERT INTO observations_fts(rowid, content) VALUES (new.rowid, new.content);
END;

CREATE TRIGGER observations_ad AFTER DELETE ON observations BEGIN
    INSERT INTO observations_fts(observations_fts, rowid, content) VALUES ('delete', old.rowid, old.content);
END;

CREATE TRIGGER observations_au AFTER UPDATE OF content ON observations BEGIN
    INSERT INTO observations_fts(observations_fts, rowid, content) VALUES ('delete', old.rowid, old.content);
    INSERT INTO observations_fts(rowid, content) VALUES (new.rowid, new.content);
END;

CREATE TABLE schema_version (
    id          TEXT    PRIMARY KEY CHECK (id = 'schema'),
    version     INTEGER NOT NULL,
    applied_at  TEXT    NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

INSERT INTO schema_version (id, version) VALUES ('schema', 1);
